# Generated by Django 4.2.1 on 2023-06-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
