# Generated by Django 4.2.1 on 2023-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_last_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
